FROM openjdk:11-jdk-slim as builder

WORKDIR /minecraft
ADD https://papermc.io/api/v1/paper/1.16.1/86/download paper.jar
RUN java -jar paper.jar

FROM openjdk:8-jdk-slim

EXPOSE 25565
WORKDIR /opt/spigot
COPY --from=builder /minecraft/cache/patched*.jar /opt/spigot/spigot.jar

CMD ["java", "-jar", "-Dcom.mojang.eula.agree=true", "spigot.jar", "-nogui"]
